### ISSUE TITLE
Idea para Trivia

### ISSUE THREAD

**Issue by Aletzzz** [Ianskev/Trivia-IanKevin#1]
![Recomendacion para trivia](https://user-images.githubusercontent.com/113266732/190884243-0bc9f7fb-3008-4df2-b2ba-9c44aa3d3e01.jpg)
 
Estaría genial que se agregue una respuesta secreta que de más puntos, de esa forma aumentaría el disfrute de la experiencia realizando la trivia

**Comment by Ianskev** [comment]
¡Hola Alex!
Muchas gracias por tu idea, ya la implementé junto con un par de características más, sí tienes alguna otra sugerencia o algún problema que pueda solucionar me avisas, gracias

Saludos,
Ian Kevin
